import { Knex } from "knex";
import { ETableNames } from "../ETableNames";








export const seed = async (knex: Knex) => {
   const [{ count }] = await knex(ETableNames.CIDADE).count<[{count: number}]>('* as count');
   if(!Number.isInteger(count) || Number(count) > 0) return;

    const cidadesToInsert = cidadesSP.map((nomeDaCidade) => ({ nome: nomeDaCidade }));
    await knex(ETableNames.CIDADE).insert(cidadesToInsert);
};


const cidadesSP = [
    'Adamantina',
    'Adolfo',
    'Aguaí',
    'Águas da Prata',
    'Águas de Lindóia',
    'Águas de Santa Bárbara',
    'Águas de São Pedro',
    'Agudos',
    'Alambari',
    'Alfredo Marcondes',
    'Altair',
    'Altinópolis',
    'Alto Alegre',
    'Alumínio',
    'Álvares Florence',
    'Álvares Machado',
    'Álvaro de Carvalho',
    'Alvinlândia',
    'Americana',
    'Américo Brasiliense',
    'Américo de Campos',
    'Amparo',
    'Analândia',
    'Andradina',
    'Angatuba',
    'Anhembi',
    'Anhumas',
    'Aparecida',
    'Aparecida d\'Oeste',
    'Apiaí',
    'Araçariguama',
    'Araçatuba',
    'Araçoiaba da Serra',
    'Aramina',
    'Arandu',
    'Arapeí',
    'Araraquara',
    'Araras',
    'Arco-Íris',
    'Arealva',
    'Areias',
    'Areiópolis',
    'Ariranha',
    'Artur Nogueira',
    'Arujá',
    'Aspásia',
    'Assis',
    'Atibaia',
    'Auriflama',
    'Avaí',
    'Avanhandava',
    'Avaré',
    'Bady Bassitt',
    'Balbinos',
    'Bálsamo',
    'Bananal',
    'Barão de Antonina',
    'Barbosa',
    'Bariri',
    'Barra Bonita',
    'Barra do Chapéu',
    'Barra do Turvo',
    'Barretos',
    'Barrinha',
    'Barueri',
    'Bastos',
    'Batatais',
    'Bauru',
    'Bebedouro',
    'Bento de Abreu',
    'Bernardino de Campos',
    'Bertioga',
    'Bilac',
    'Birigui',
    'Biritiba-Mirim',
    'Boa Esperança do Sul',
    'Bocaina',
    'Bofete',
    'Boituva',
    'Bom Jesus dos Perdões',
    'Bom Sucesso de Itararé',
    'Borá',
    'Boracéia',
    'Borborema',
    'Borebi',
    'Botucatu',
    'Bragança Paulista',
    'Braúna',
    'Brejo Alegre',
    'Brodowski',
    'Brotas',
    'Buri',
    'Buritama',
    'Buritizal',
    'Cabrália Paulista',
    'Cabreúva',
    'Caçapava',
    'Cachoeira Paulista',
    'Caconde',
    'Cafelândia',
    'Caiabu',
    'Caieiras',
    'Caiuá',
    'Cajamar',
    'Cajati',
    'Cajobi',
    'Cajuru',
    'Campina do Monte Alegre',
    'Campinas',
    'Campo Limpo Paulista',
    'Campos do Jordão',
    'Campos Novos Paulista',
    'Cananéia',
    'Canas',
    'Cândido Mota',
    'Cândido Rodrigues',
    'Canitar',
    'Capão Bonito',
    'Capela do Alto',
    'Capivari',
    'Caraguatatuba',
    'Carapicuíba',
    'Cardoso',
    'Casa Branca',
    'Cássia dos Coqueiros',
    'Castilho',
    'Catanduva',
    'Catiguá',
    'Cedral',
    'Cerqueira César',
    'Cerquilho',
    'Cesário Lange',
    'Charqueada',
    'Chavantes',
    'Clementina',
    'Colina',
    'Colômbia',
    'Conchal',
    'Conchas',
    'Cordeirópolis',
    'Coroados',
    'Coronel Macedo',
    'Corumbataí',
    'Cosmópolis',
    'Cosmorama',
    'Cotia',
    'Cravinhos',
    'Cristais Paulista',
    'Cruzália',
    'Cruzeiro',
    'Cubatão',
    'Cunha',
    'Descalvado',
    'Diadema',
    'Dirce Reis',
    'Divinolândia',
    'Dobrada',
    'Dois Córregos',
    'Dolcinópolis',
    'Dourado',
    'Dracena',
    'Duartina',
    'Dumont',
    'Echaporã',
    'Eldorado',
    'Elias Fausto',
    'Elisiário',
    'Embaúba',
    'Embu das Artes',
    'Embu-Guaçu',
    'Emilianópolis',
    'Engenheiro Coelho',
    'Espírito Santo do Pinhal',
    'Espírito Santo do Turvo',
    'Estiva Gerbi',
    'Estrela d\'Oeste',
    'Estrela do Norte',
    'Euclides da Cunha Paulista',
    'Fartura',
    'Fernando Prestes',
    'Fernandópolis',
    'Fernão',
    'Ferraz de Vasconcelos',
    'Flora Rica',
    'Floreal',
    'Flórida Paulista',
    'Florínia',
    'Franca',
    'Francisco Morato',
    'Franco da Rocha',
    'Gabriel Monteiro',
    'Gália',
    'Garça',
    'Gastão Vidigal',
    'Gavião Peixoto',
    'General Salgado',
    'Getulina',
    'Glicério',
    'Guaiçara',
    'Guaimbê',
    'Guaíra',
    'Guapiaçu',
    'Guapiara',
    'Guará',
    'Guaraçaí',
    'Guaraci',
    'Guarani d\'Oeste',
    'Guarantã',
    'Guararapes',
    'Guararema',
    'Guaratinguetá',
    'Guareí',
    'Guariba',
    'Guarujá',
    'Guarulhos',
    'Guatapará',
    'Guzolândia',
    'Herculândia',
    'Holambra',
    'Hortolândia',
    'Iacanga',
    'Iacri',
    'Iaras',
    'Ibaté',
    'Ibirá',
    'Ibirarema',
    'Ibitinga',
    'Ibiúna',
    'Icém',
    'Iepê',
    'Igaraçu do Tietê',
    'Igarapava',
    'Igaratá',
    'Iguape',
    'Ilha Comprida',
    'Ilha Solteira',
    'Ilhabela',
    'Indaiatuba',
    'Indiana',
    'Indiaporã',
    'Inúbia Paulista',
    'Ipaussu',
    'Iperó',
    'Ipeúna',
    'Ipiguá',
    'Iporanga',
    'Ipuã',
    'Iracemápolis',
    'Irapuã',
    'Irapuru',
    'Itaberá',
    'Itaí',
    'Itajobi',
    'Itaju',
    'Itanhaém',
    'Itaóca',
    'Itapecerica da Serra',
    'Itapetininga',
    'Itapeva',
    'Itapevi',
    'Itapira',
    'Itapirapuã Paulista',
    'Itápolis',
    'Itaporanga',
    'Itapuí',
    'Itapura',
    'Itaquaquecetuba',
    'Itararé',
    'Itariri',
    'Itatiba',
    'Itatinga',
    'Itirapina',
    'Itirapuã',
    'Itobi',
    'Itu',
    'Itupeva',
    'Ituverava',
    'Jaborandi',
    'Jaboticabal',
    'Jacareí',
    'Jaci',
    'Jacupiranga',
    'Jaguariúna',
    'Jales',
    'Jambeiro',
    'Jandira',
    'Jardinópolis',
    'Jarinu',
    'Jaú',
    'Jeriquara',
    'Joanópolis',
    'João Ramalho',
    'José Bonifácio',
    'Júlio Mesquita',
    'Jumirim',
    'Jundiaí',
    'Junqueirópolis',
    'Juquiá',
    'Juquitiba',
    'Lagoinha',
    'Laranjal Paulista',
    'Lavínia',
    'Lavrinhas',
    'Leme',
    'Lençóis Paulista',
    'Limeira',
    'Lindóia',
    'Lins',
    'Lorena',
    'Lourdes',
    'Louveira',
    'Lucélia',
    'Lucianópolis',
    'Luís Antônio',
    'Luiziânia',
    'Lupércio',
    'Lutécia',
    'Macatuba',
    'Macaubal',
    'Macedônia',
    'Magda',
    'Mairinque',
    'Mairiporã',
    'Manduri',
    'Marabá Paulista',
    'Maracaí',
    'Marapoama',
    'Mariápolis',
    'Marília',
    'Marinópolis',
    'Martinópolis',
    'Matão',
    'Mauá',
    'Mendonça',
    'Meridiano',
    'Mesópolis',
    'Miguelópolis',
    'Mineiros do Tietê',
    'Mira Estrela',
    'Miracatu',
    'Mirandópolis',
    'Mirante do Paranapanema',
    'Mirassol',
    'Mirassolândia',
    'Mococa',
    'Mogi das Cruzes',
    'Mogi Guaçu',
    'Moji Mirim',
    'Mombuca',
    'Monções',
    'Mongaguá',
    'Monte Alegre do Sul',
    'Monte Alto',
    'Monte Aprazível',
    'Monte Azul Paulista',
];